# Generated by Django 5.0.2 on 2024-04-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
